### PR TITLE
Halnur

### PR DESCRIPTION
**Pull request by halnur312**
Please check FINRA task solution

### CODE REVIEW

**Comment by Lejlam7** [comment]
looks good :)

**Review by raminka07 — COMMENTED** [review]
looks good)

**Review by raminka07 — APPROVED** [review]
Approved

**Review by donnellreuben — APPROVED** [review]
Line 19 and line 20 spacing before "else if" for readability, also is this a function/method??


otherwise looks good 😃

**Review by rashaaezz — APPROVED** [review]
well done

**Pull request merged**
